HiramWeyman/front_cognos

src/app/models/Consumo.ts, src/app/models/Previo.ts, src/app/models/ProbMed.ts, src/app/pages/antecedentes/antecedentes.component.html, src/app/pages/antecedentes/antecedentes.component.ts, src/app/services/antecedentes.service.ts
=> antecedentes completo

src/app/models/Tratamiento.ts, src/app/pages/pacientes/pacientes.component.ts, src/app/pages/tratamiento/tratamiento.component.html, src/app/pages/tratamiento/tratamiento.component.ts, src/app/services/tratamiento.service.ts
=> Tratamiento

src/app/models/Consulta.ts, src/app/models/ProbObj.ts, src/app/pages/analisisfunc/analisisfunc.component.html, src/app/pages/analisisfunc/analisisfunc.component.scss, src/app/pages/areasconsiderar/areasconsiderar.component.html, src/app/pages/areasconsiderar/areasconsiderar.component.scss, src/app/pages/problematica/problematica.component.html, src/app/pages/problematica/problematica.component.scss, src/app/pages/problematica/problematica.component.ts, src/app/services/problematica.service.ts
modulo de problematica y ajustes
=> modulo de problematica y ajustes

src/app/models/LineaVida.ts, src/app/pages/lineavida/lineavida.component.html, src/app/pages/lineavida/lineavida.component.ts, src/app/services/lineavida.service.ts
=> Modulo Linea de vida

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/pages/analisisfunc/analisisfunc.component.ts, src/app/pages/antecedentes/antecedentes.component.ts, src/app/pages/areasconsiderar/areasconsiderar.component.ts, src/app/pages/datosexp/datosexp.component.html, src/app/pages/datosexp/datosexp.component.ts, src/app/pages/diagnostico/diagnostico.component.ts, src/app/pages/evoproblema/evoproblema.component.ts, src/app/pages/generales/generales.component.ts, src/app/pages/lineavida/lineavida.component.ts, src/app/pages/problematica/problematica.component.ts, src/app/pages/regsesion/regsesion.component.html, src/app/pages/regsesion/regsesion.component.scss, src/app/pages/regsesion/regsesion.component.spec.ts, src/app/pages/regsesion/regsesion.component.ts, src/app/pages/saludfisica/saludfisica.component.ts, src/app/pages/sesiones/sesiones.component.html, src/app/pages/tratamiento/tratamiento.component.ts
Se arreglo que quede seleccionado la tab en la que se trabaja
=> index de mat table

src/app/models/Evolucion.ts, src/app/models/Otras.ts, src/app/models/Pacientes.ts, src/app/models/ProbObj.ts, src/app/modules/main/header/header.component.ts, src/app/pages/analisisfunc/analisisfunc.component.ts, src/app/pages/antecedentes/antecedentes.component.ts, src/app/pages/areasconsiderar/areasconsiderar.component.html, src/app/pages/areasconsiderar/areasconsiderar.component.ts, src/app/pages/datosexp/datosexp.component.html, src/app/pages/diagnostico/diagnostico.component.ts, src/app/pages/evoproblema/evoproblema.component.html, src/app/pages/evoproblema/evoproblema.component.ts, src/app/pages/generales/generales.component.ts, src/app/pages/lineavida/lineavida.component.ts, src/app/pages/pacientes/pacientes.component.ts, src/app/pages/problematica/problematica.component.html, src/app/pages/problematica/problematica.component.ts, src/app/pages/regpaciente/regpaciente.component.html, src/app/pages/regpaciente/regpaciente.component.ts, src/app/pages/saludfisica/saludfisica.component.ts, src/app/pages/sesiones/sesiones.component.ts, src/app/pages/tratamiento/tratamiento.component.ts, src/app/services/app.service.ts, src/app/services/pacientes.service.ts
Se corrigio Evolucion del problema y areas a considerar, tambien se agrego el tutor al registro del paciente
=> corrigiendo modelos

src/app/models/Comentarios.ts, src/app/pages/analisisfunc/analisisfunc.component.html, src/app/pages/analisisfunc/analisisfunc.component.ts, src/app/pages/antecedentes/antecedentes.component.html, src/app/pages/antecedentes/antecedentes.component.ts, src/app/pages/areasconsiderar/areasconsiderar.component.html, src/app/pages/areasconsiderar/areasconsiderar.component.ts, src/app/pages/datosexp/datosexp.component.html, src/app/pages/diagnostico/diagnostico.component.html, src/app/pages/diagnostico/diagnostico.component.ts, src/app/pages/editsesion/editsesion.component.html, src/app/pages/evoproblema/evoproblema.component.html, src/app/pages/evoproblema/evoproblema.component.ts, src/app/pages/formcaso/formcaso.component.html, src/app/pages/formcaso/formcaso.component.ts, src/app/pages/generales/generales.component.html, src/app/pages/generales/generales.component.ts, src/app/pages/lineavida/lineavida.component.html, src/app/pages/lineavida/lineavida.component.ts, src/app/pages/problematica/problematica.component.html, src/app/pages/problematica/problematica.component.ts, src/app/pages/saludfisica/saludfisica.component.html, src/app/pages/saludfisica/saludfisica.component.ts, src/app/pages/tratamiento/tratamiento.component.html, src/app/pages/tratamiento/tratamiento.component.ts, src/app/services/comentarios.service.ts, src/app/services/sharednumber.service.ts
Funcionalidad de comentarios terminada
=> Funcionalidad de comentarios terminada

package-lock.json, package.json, src/app/app.module.ts, src/app/models/Creencias.ts, src/app/pages/enviopruebas/enviopruebas.component.html, src/app/pages/enviopruebas/enviopruebas.component.ts, src/app/pages/ideasirracionales/ideasirracionales.component.html, src/app/pages/ideasirracionales/ideasirracionales.component.ts, src/app/pages/verinforme/verinforme.component.html, src/app/pages/verinforme/verinforme.component.ts, src/app/services/creencias.service.ts, src/app/services/enviarpruebas.service.ts
Se termino la funcion de archivos
=> Se termino la funcion de archivos

src/app/pages/enviopruebas/enviopruebas.component.html, src/app/pages/verinforme/verinforme.component.html, src/app/pages/verinforme/verinforme.component.ts
ya esta la imagen en el informe
=> ya esta la imagen en el informe

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/models/ResultadosSCL.ts, src/app/pages/enviopruebas/enviopruebas.component.html, src/app/pages/resultados-scl/resultados-scl.component.html, src/app/pages/resultados-scl/resultados-scl.component.spec.ts, src/app/pages/resultados-scl/resultados-scl.component.ts, src/app/services/resultados.service.ts
=> Resultados SCL terminados

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/models/ResultadosCree.ts, src/app/models/resultadosBDIDP.ts, src/app/pages/enviopruebas/enviopruebas.component.html, src/app/pages/resultados-bdidp/resultados-bdidp.component.html, src/app/pages/resultados-bdidp/resultados-bdidp.component.spec.ts, src/app/pages/resultados-bdidp/resultados-bdidp.component.ts, src/app/pages/resultados-cree/resultados-cree.component.html, src/app/pages/resultados-cree/resultados-cree.component.spec.ts, src/app/pages/resultados-cree/resultados-cree.component.ts, src/app/services/resultados.service.ts
Resultados BDI y Creencias ellis Completados y terminados
=> Resultados BDI y Creencias ellis Completados

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/models/RessultadosSCID.ts, src/app/pages/enviopruebas/enviopruebas.component.html, src/app/pages/resultados-scid/resultados-scid.component.html, src/app/pages/resultados-scid/resultados-scid.component.spec.ts, src/app/pages/resultados-scid/resultados-scid.component.ts, src/app/services/resultados.service.ts
=> resultados de scid completos

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/pages/enviopruebas/enviopruebas.component.html, src/app/pages/resultados-isra/resultados-isra.component.html, src/app/pages/resultados-isra/resultados-isra.component.scss, src/app/pages/resultados-isra/resultados-isra.component.spec.ts, src/app/pages/resultados-isra/resultados-isra.component.ts, src/app/services/resultados.service.ts
primera parte del proyecto terminada
=> primera parte del proyecto terminada

src/app/pages/pacientes/pacientes.component.ts, src/app/services/pacientes.service.ts, src/environments/environment.ts
=> Querys Perfiles

src/app/modules/login/login.component.html, src/app/modules/login/login.component.ts, src/app/pages/areasconsiderar/areasconsiderar.component.ts, src/app/pages/editsesion/editsesion.component.html, src/app/pages/editsesion/editsesion.component.ts, src/app/pages/generales/generales.component.html, src/app/pages/regsesion/regsesion.component.html, src/app/pages/regsesion/regsesion.component.ts, src/app/pages/sesiones/sesiones.component.html, src/app/pages/sesiones/sesiones.component.ts, src/app/pages/verinforme/verinforme.component.html, src/app/services/otras.service.ts
=> Arreglo de bugs

src/app/models/EnvioCorreo.ts, src/app/modules/forgot-password/forgot-password.component.ts, src/app/modules/login/login.component.ts, src/app/modules/register/register.component.ts, src/app/pages/repsesion/repsesion.component.html, src/app/services/app.service.ts, src/environments/environment.ts
=> ultimos cambios

src/environments/environment.ts
=> Cambio de ruta

src/environments/environment.ts
=> Manuel dev comparte a Hiram

src/app/models/AnalisisFU.ts, src/environments/environment.ts
Usando solo la appvUsando solo la app
=> Manuel dev - camparte desde app a Hiram

src/app/models/AnalisisFU.ts
Se completo Comentario Analisis Funcional
=> Hiram Comparte desde App
